library(readxl)
library(dplyr)
library(tidyr)
data_raw<-read_excel("D:/JUMP/胰腺癌.xlsx")
data_clean<-data_raw%>%filter(Diagnosis=="PDAC")
data_clean<-data_clean%>%mutate(status=ifelse(`Survival Status`=="Deceased",1,0))
table(data_clean$status)
data_clean <- data_clean %>%mutate(stage_clean = case_when(`Tumor Stage` %in% c("IA", "IB") ~ "I",`Tumor Stage` == "I" ~ "I",`Tumor Stage` %in% c("IIA", "IIB") ~ "II",`Tumor Stage` == "III" ~ "III",`Tumor Stage` == "IV" ~ "IV",TRUE ~ NA_character_))
data_clean<-data_clean%>%mutate(stage_group=case_when(stage_clean%in%c("I","II")~"Early",stage_clean%in%c("III","IV")~"Late",TRUE~NA_character_))
table(data_clean$stage_clean, useNA = "ifany")
table(data_clean$stage_group, useNA = "ifany")
class(data_clean$Age)
data_clean$Sex<-as.factor(data_clean$Sex)
class(data_clean$Sex)
table(data_clean$Sex)
summary(data_clean$Age)
hist(data_clean$Age,main = "年龄分布",xlab = "年龄")
data_clean<-data_clean%>%mutate(diabetes=case_when(`Diabetes History`=="Yes"~"Yes",`Diabetes History`=="No"~"No",TRUE~NA_character_))
data_clean<-data_clean%>%mutate(kras=case_when(`Missense Mutation - KRAS`=="No"~"Wildtype",`Missense Mutation - KRAS`!="No"&!is.na(`Missense Mutation - KRAS`)~"Mutant",TRUE~NA_character_))
table(data_clean$diabetes,useNA = "ifany")
table(data_clean$kras,useNA = "ifany")
data_final<-data_clean%>%filter(!is.na(status),!is.na(`Survival Time`),!is.na(stage_group),!is.na(Age),!is.na(Sex))
print(paste("最终样本量:", nrow(data_final)))
print("早期/晚期分布:")
table(data_final$stage_group)
print("生存状态分布 (0=存活, 1=死亡):")
table(data_final$status)
